# Twitter accounts and search terms for sentiment analysis
# Used by polymarket-sentiment scraper

users:
  - name: FirstSquawk
    weight: 1.0
    description: "Financial breaking news"
  - name: realDonaldTrump
    weight: 0.8
    description: "Political sentiment"
  - name: ZeroHedge
    weight: 0.9
    description: "Market sentiment"

terms:
  - query: "ceasefire gaza"
    weight: 1.2
    description: "Middle East conflict sentiment"
  - query: "federal reserve rate"
    weight: 1.0
    description: "Fed policy sentiment"
  - query: "polymarket"
    weight: 0.7
    description: "Platform mentions"
